# Generated by Django 4.2.25 on 2025-10-28 14:51

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_product_active_alter_product_barcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('ENTRADA', 'ENTRADA'), ('SAIDA', 'SAIDA'), ('AJUSTE', 'AJUSTE')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_current', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('minimum', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('maximum', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('ZERADO', 'ZERADO'), ('ABAIXO', 'ABAIXO'), ('OK', 'OK'), ('ACIMA', 'ACIMA')], db_index=True, default='ZERADO', max_length=10)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalog.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
