# Generated by Django 4.2.25 on 2025-10-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['product', 'active'], name='promo_prod_active_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['start_date'], name='promo_start_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['end_date'], name='promo_end_idx'),
        ),
    ]
