openapi: 3.0.3
info:
  title: MVPSale API - Sale endpoints
  version: 1.0.0
  description: Sale-related endpoints extracted from the full schema
paths:
  /api/sale/orders/:
    get:
      operationId: api_sale_orders_list
      summary: Listar pedidos
      parameters:
      - name: ordering
        required: false
        in: query
        description: Qual campo usar ao ordenar os resultados.
        schema:
          type: string
      - name: page
        required: false
        in: query
        description: Um número de página dentro do conjunto de resultados paginado.
        schema:
          type: integer
      - name: search
        required: false
        in: query
        description: Um termo de busca.
        schema:
          type: string
      tags:
      - sale
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '../../schema.yml#/components/schemas/PaginatedOrderList'
          description: ''
    post:
      operationId: api_sale_orders_create
      summary: Criar pedido
      tags:
      - sale
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../schema.yml#/components/schemas/Order'
          application/x-www-form-urlencoded:
            schema:
              $ref: '../../schema.yml#/components/schemas/Order'
          multipart/form-data:
            schema:
              $ref: '../../schema.yml#/components/schemas/Order'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '../../schema.yml#/components/schemas/Order'
          description: ''
  /api/sale/orders/{id}/:
    get:
      operationId: api_sale_orders_retrieve
      summary: Detalhar pedido
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este order.
        required: true
      tags:
      - sale
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '../../schema.yml#/components/schemas/Order'
          description: ''
    put:
      operationId: api_sale_orders_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este order.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../schema.yml#/components/schemas/Order'
          application/x-www-form-urlencoded:
            schema:
              $ref: '../../schema.yml#/components/schemas/Order'
          multipart/form-data:
            schema:
              $ref: '../../schema.yml#/components/schemas/Order'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '../../schema.yml#/components/schemas/Order'
          description: ''
    patch:
      operationId: api_sale_orders_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este order.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../schema.yml#/components/schemas/PatchedOrder'
          application/x-www-form-urlencoded:
            schema:
              $ref: '../../schema.yml#/components/schemas/PatchedOrder'
          multipart/form-data:
            schema:
              $ref: '../../schema.yml#/components/schemas/PatchedOrder'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '../../schema.yml#/components/schemas/Order'
          description: ''
    delete:
      operationId: api_sale_orders_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este order.
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/sale/orders/{id}/action/:
    post:
      operationId: api_sale_orders_action_create
      summary: Confirmar ou cancelar pedido
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este order.
        required: true
      tags:
      - sale
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../schema.yml#/components/schemas/OrderAction'
          application/x-www-form-urlencoded:
            schema:
              $ref: '../../schema.yml#/components/schemas/OrderAction'
          multipart/form-data:
            schema:
              $ref: '../../schema.yml#/components/schemas/OrderAction'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '../../schema.yml#/components/schemas/Order'
          description: ''
  /api/sale/orders/{id}/add-item/:
    post:
      operationId: api_sale_orders_add_item_create
      summary: Adicionar item
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este order.
        required: true
      tags:
      - sale
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../schema.yml#/components/schemas/AddItem'
          application/x-www-form-urlencoded:
            schema:
              $ref: '../../schema.yml#/components/schemas/AddItem'
          multipart/form-data:
            schema:
              $ref: '../../schema.yml#/components/schemas/AddItem'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '../../schema.yml#/components/schemas/OrderItem'
          description: ''
  /api/sale/orders/{id}/items/:
    get:
      operationId: api_sale_orders_items_list
      summary: Listar itens do pedido
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este order.
        required: true
      - name: ordering
        required: false
        in: query
        description: Qual campo usar ao ordenar os resultados.
        schema:
          type: string
      - name: page
        required: false
        in: query
        description: Um número de página dentro do conjunto de resultados paginado.
        schema:
          type: integer
      - name: search
        required: false
        in: query
        description: Um termo de busca.
        schema:
          type: string
      tags:
      - sale
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '../../schema.yml#/components/schemas/PaginatedOrderItemList'
          description: ''
  /api/sale/orders/{id}/items/{item_id}/:
    put:
      operationId: api_sale_orders_items_update
      summary: Atualizar item do pedido
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este order.
        required: true
      - in: path
        name: item_id
        schema:
          type: string
        required: true
      tags:
      - sale
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../schema.yml#/components/schemas/OrderItem'
          application/x-www-form-urlencoded:
            schema:
              $ref: '../../schema.yml#/components/schemas/OrderItem'
          multipart/form-data:
            schema:
              $ref: '../../schema.yml#/components/schemas/OrderItem'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '../../schema.yml#/components/schemas/OrderItem'
          description: ''
    patch:
      operationId: api_sale_orders_items_partial_update
      summary: Atualizar item do pedido
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este order.
        required: true
      - in: path
        name: item_id
        schema:
          type: string
        required: true
      tags:
      - sale
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../schema.yml#/components/schemas/PatchedOrderItem'
          application/x-www-form-urlencoded:
            schema:
              $ref: '../../schema.yml#/components/schemas/PatchedOrderItem'
          multipart/form-data:
            schema:
              $ref: '../../schema.yml#/components/schemas/PatchedOrderItem'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '../../schema.yml#/components/schemas/OrderItem'
          description: ''
    delete:
      operationId: api_sale_orders_items_destroy
      summary: Excluir item do pedido
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este order.
        required: true
      - in: path
        name: item_id
        schema:
          type: string
        required: true
      tags:
      - sale
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body

  # v1 variants (removed from this app file to avoid unresolved $ref)
  # If you need to keep v1 compatibility, add a dedicated schema_v1.yml or
  # create explicit duplicated paths here that reference the same components.

components: {}
