# Generated by Django 4.2.25 on 2025-11-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_order_uuid_orderitem_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(db_index=True, default='carrinho', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='sales_order',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
