# Generated by Django 4.2.25 on 2025-10-28 14:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('catalog', '0002_alter_product_active_alter_product_barcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_code', models.CharField(db_index=True, max_length=60)),
                ('universal_code', models.CharField(blank=True, max_length=60)),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('ncm', models.CharField(blank=True, max_length=10)),
                ('cfop', models.CharField(blank=True, max_length=10)),
                ('cest', models.CharField(blank=True, max_length=10)),
                ('icms_cst', models.CharField(blank=True, max_length=5)),
                ('icms_origem', models.CharField(blank=True, max_length=5)),
                ('ipi_cenq', models.CharField(blank=True, max_length=5)),
                ('ipi_cst', models.CharField(blank=True, max_length=5)),
                ('pis_cst', models.CharField(blank=True, max_length=5)),
                ('pis_aliq', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('cofins_cst', models.CharField(blank=True, max_length=5)),
                ('cofins_aliq', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('uCom', models.CharField(blank=True, max_length=6)),
                ('uTrib', models.CharField(blank=True, max_length=6)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='catalog.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='people.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=20)),
                ('series', models.CharField(blank=True, max_length=10)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('xml', models.TextField()),
                ('pdf_path', models.CharField(blank=True, max_length=255)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='people.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=10)),
                ('due_date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(default='PENDENTE', max_length=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='purchase.purchaseinvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='supplierproduct',
            constraint=models.UniqueConstraint(fields=('supplier', 'product'), name='uniq_supplier_product'),
        ),
    ]
