# Generated by Django 4.2.25 on 2025-10-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.UniqueConstraint(fields=('supplier', 'number', 'series'), name='uniq_invoice_supplier_number_series'),
        ),
    ]
