# Generated by Django 4.2.25 on 2025-10-29 17:42

# Reworked migration: add uuid fields as nullable, populate unique values, then alter to unique non-null
from django.db import migrations, models
import uuid


def populate_uuids(apps, schema_editor):
    PurchaseInstallment = apps.get_model('purchase', 'PurchaseInstallment')
    PurchaseInvoice = apps.get_model('purchase', 'PurchaseInvoice')
    SupplierProduct = apps.get_model('purchase', 'SupplierProduct')

    for Model in (PurchaseInstallment, PurchaseInvoice, SupplierProduct):
        for obj in Model.objects.all():
            if not getattr(obj, 'uuid', None):
                obj.uuid = uuid.uuid4()
                obj.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_purchaseinvoice_uniq_invoice_supplier_number_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinstallment',
            name='uuid',
            field=models.UUIDField(db_index=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='uuid',
            field=models.UUIDField(db_index=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='uuid',
            field=models.UUIDField(db_index=True, null=True, editable=False),
        ),
        migrations.RunPython(populate_uuids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='purchaseinstallment',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
