# Generated by Django 4.2.25 on 2025-10-28 15:23

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('type', models.CharField(choices=[('cash', 'Dinheiro'), ('card_credit', 'Cartão Crédito'), ('card_debit', 'Cartão Débito'), ('pix', 'PIX'), ('boleto', 'Boleto'), ('voucher', 'Voucher'), ('credit_note', 'Crédito Loja')], max_length=20)),
                ('fee_percent', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6)),
                ('fee_fixed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('settlement_days', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('PAGO', 'PAGO'), ('ATRASADO', 'ATRASADO'), ('ESTORNADO', 'ESTORNADO')], db_index=True, default='PENDENTE', max_length=12)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='payment.paymentmethod')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paid_date', models.DateField()),
                ('external_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payment.receivable')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
