# Generated by Django 4.2.25 on 2025-10-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='auto_settle',
            field=models.BooleanField(default=False),
        ),
    ]
