# Generated by Django 4.2.25 on 2025-10-29 17:42

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentmethod_auto_settle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardBrand',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='receivable',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='CardFeeTier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('card_credit', 'Crédito'), ('card_debit', 'Débito')], max_length=20)),
                ('installments_min', models.PositiveIntegerField(default=1)),
                ('installments_max', models.PositiveIntegerField(default=1)),
                ('fee_percent', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6)),
                ('fee_fixed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('settlement_days', models.PositiveIntegerField(default=30)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_tiers', to='payment.cardbrand')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cardfeetier',
            constraint=models.CheckConstraint(check=models.Q(('installments_min__gte', 1)), name='fee_min_ge_1'),
        ),
        migrations.AddConstraint(
            model_name='cardfeetier',
            constraint=models.CheckConstraint(check=models.Q(('installments_max__gte', models.F('installments_min'))), name='fee_max_ge_min'),
        ),
    ]
