# Generated by Django 4.2.25 on 2025-11-04 22:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_cardbrand_paymentevent_uuid_paymentmethod_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardfeetier',
            name='fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
    ]
