# Generated by Django 4.2.25 on 2025-10-28 15:47

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale', '0002_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('ie', models.CharField(blank=True, max_length=20)),
                ('regime_tributario', models.CharField(blank=True, max_length=20)),
                ('razao_social', models.CharField(max_length=200)),
                ('nome_fantasia', models.CharField(blank=True, max_length=200)),
                ('logradouro', models.CharField(blank=True, max_length=200)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('bairro', models.CharField(blank=True, max_length=120)),
                ('cidade', models.CharField(blank=True, max_length=120)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=9)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NFeInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('env', models.CharField(default='homolog', max_length=10)),
                ('provider', models.CharField(default='focus', max_length=20)),
                ('ref', models.CharField(max_length=60, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('SUBMITTED', 'SUBMITTED'), ('AUTHORIZED', 'AUTHORIZED'), ('REJECTED', 'REJECTED'), ('CANCELED', 'CANCELED')], db_index=True, default='DRAFT', max_length=12)),
                ('chave', models.CharField(blank=True, db_index=True, max_length=50)),
                ('protocolo', models.CharField(blank=True, max_length=50)),
                ('cStat', models.CharField(blank=True, max_length=10)),
                ('xMotivo', models.CharField(blank=True, max_length=255)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('danfe_url', models.URLField(blank=True)),
                ('xml', models.TextField(blank=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nfe_invoices', to='nfe.company')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfe_invoices', to='sale.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NFeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(max_length=30)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('protocolo', models.CharField(blank=True, max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='SUBMITTED', max_length=20)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='nfe.nfeinvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
